const EXPERIENCE_FETCH_REQUEST = 'EXPERIENCE_FETCH_REQUEST';
const EXPERIENCE_FETCH_SUCCESS = 'EXPERIENCE_FETCH_SUCCESS';
const EXPERIENCE_FETCH_ERROR = 'EXPERIENCE_FETCH_ERROR';

export {EXPERIENCE_FETCH_ERROR, EXPERIENCE_FETCH_REQUEST, EXPERIENCE_FETCH_SUCCESS};

