const HOME_FETCH_REQUEST = 'HOME_FETCH_REQUEST';
const HOME_FETCH_SUCCESS = 'HOME_FETCH_SUCCESS';
const HOME_FETCH_ERROR = 'HOME_FETCH_ERROR';

export {HOME_FETCH_ERROR, HOME_FETCH_REQUEST, HOME_FETCH_SUCCESS};